language: ruby
os: linux
dist: focal
cache:
  bundler: true
  directories:
  - _site
rvm:
- 2.7
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
- bundle exec jekyll build --incremental
- bundle exec htmlproofer ./_site --check-html --url-ignore /twitter.com\/mthssdrbrg/
