language: ruby
sudo: false
cache:
  bundler: true
  directories:
  - _site
rvm:
- 2.7
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
- bundle exec jekyll build --incremental
- bundle exec htmlproofer ./_site --check-html
