permalink: /:year/:i_month/:i_day/:title
exclude: [Gemfile, Gemfile.lock, README.md]
paginate: 5
sass:
  style: :compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
