permalink: /:year/:i_month/:i_day/:title/
exclude: [Gemfile, Gemfile.lock, README.md, vendor]
paginate: 3
gems:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-feed
markdown: redcarpet
redcarpet:
  extensions:
    - tables
    - no_intra_emphasis
    - strikethrough
sass:
  style: :compressed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
jekyll-archives:
  enabled:
    - tags
  layout: tag
  permalinks:
    tag: '/tag/:name/'
